.github/workflows/ci.yml, src/DotNetLightning.Core/Chain/ChainInterface.fs, src/DotNetLightning.Core/DotNetLightning.Core.fsproj, src/DotNetLightning.Core/LN/Channel.fs, src/DotNetLightning.Core/LN/ChannelTypes.fs, src/DotNetLightning.Core/Utils/Primitives.fs, tests/DotNetLightning.Core.Tests/ChannelCoreTests.fs, tests/DotNetLightning.Core.Tests/Serialization.fs, tests/DotNetLightning.Core.Tests/TransactionBolt3TestVectorTests.fs, tests/DotNetLightning.Infrastructure.Tests/Constants.fs
NOTE: do not merge yet, somehow tests not passing (https://github.com/knocte/DotNetLightning/runs/228729412), help.
=> Stop using NBitcoin fork

src/DotNetLightning.Core/DotNetLightning.Core.fsproj, tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj, tests/DotNetLightning.Infrastructure.Tests/DotNetLightning.Infrastructure.Tests.fsproj
Fixes https://github.com/joemphilips/DotNetLightning/issues/14
=> Core: mark refs as non-Nuget refs

tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj
Necessary to run test using "dotnet test". If I don't do this, the project is simply skipped (NET Core 3).
=> Reference Microsoft.NET.Test.Sdk

src/DotNetLightning.Core/LN/Channel.fs
I discovered this because the remote couldn't validate the commitment signature we send in funding_created. Tested with Electrum and LND on regtest.
<s>The tests may fail, but I think that is unrelated.</s> (EDIT: Was not unrelated, tests fixed) But if you have any suggestions I'd be happy to hear them.
=> Core: LN.Channel: Use correct keys and to_self_delay for initial commitment transactions

src/DotNetLightning.Core/LN/Channel.fs
The commitment points used are specific to each counterparty.
Note that in the calls to `makeFirstCommitTxs`, previously we would pass the remote point at line 587 as the ambiguous parameter, and at line 692 we would pass the local one. The lines can remain unchanged as you can see in this patch, but in one case, the existing point passed is the remote one, and in the other case it is the local one.
This time I ran the Infrastructure tests, and I also tested with LND.
=> Core: LN.Channel: Use both commitment points

src/DotNetLightning.Core/Utils/Primitives.fs
This version doesn't use try/with.
=> Make NodeId comparable with incompatible types

src/DotNetLightning.Core/DotNetLightning.Core.fsproj
See https://github.com/joemphilips/DotNetLightning/issues/32#issuecomment-554625165
This is placeholder PR, Please report me if you have any problem by this.
/cc @ysangkok or @knocte
=> Specify to use FSharp.Core 4.7 properly

Nuget.Config, src/Secp256k1.Net/Secp256k1.Net.csproj, tests/Secp256k1.Net.Test/Secp256k1.Net.Test.csproj
=> stop using private feed

.github/workflows/ci.yml
=> stop adding private feed in ci

.github/workflows/ci.yml, src/DotNetLightning.Core/Channel/Channel.fs, src/DotNetLightning.Core/Channel/CommitmentsModule.fs, src/DotNetLightning.Core/Serialize/Msgs.fs, src/DotNetLightning.Core/Transactions/Transactions.fs, src/DotNetLightning.Core/Utils/Primitives.fs, tests/DotNetLightning.Core.Tests/Generators/Msgs.fs, tests/DotNetLightning.Core.Tests/KeyRepositoryTests.fs, tests/DotNetLightning.Core.Tests/Serialization.fs, tests/DotNetLightning.Core.Tests/TransactionBolt3TestVectorTests.fs, tests/DotNetLightning.Infrastructure.Tests/ChannelOperationTests.fs
See each individual commit message for details.
=> Payment preimage slight refactorings

DotNetLightning.sln.DotSettings, src/DotNetLightning.Core/Channel/ChannelCommands.fs, src/DotNetLightning.Core/DotNetLightning.Core.fsproj, src/DotNetLightning.Core/Payment/PaymentRequest.fs, src/DotNetLightning.Core/Peer/Peer.fs, src/DotNetLightning.Core/Peer/PeerChannelEncryptor.fs, src/DotNetLightning.Core/Serialize/BitWriter.fs, src/DotNetLightning.Core/Serialize/Features.fs, src/DotNetLightning.Core/Serialize/LightningStream.fs, src/DotNetLightning.Core/Serialize/Msgs.fs, src/DotNetLightning.Core/Utils/Extensions.fs, src/DotNetLightning.Core/Utils/GenericTLV.fs, src/DotNetLightning.Infrastructure/ActorManagers/PeerManager.fs, src/DotNetLightning.Infrastructure/ChainConfig.fs, src/DotNetLightning.Infrastructure/Constants.fs, src/DotNetLightning.Infrastructure/DTOs/GetInfoResponse.fs, src/DotNetLightning.Infrastructure/DotNetLightningNetwork.fs, src/DotNetLightning.Infrastructure/Services/ActorManagers.fs, tests/DotNetLightning.Core.Tests/Generators/Msgs.fs, tests/DotNetLightning.Core.Tests/PaymentTests.fs, tests/DotNetLightning.Core.Tests/Serialization.fs, tests/DotNetLightning.Infrastructure.Tests/ChannelOperationTests.fs, tests/DotNetLightning.Infrastructure.Tests/PeerManagerTests.fs
=> Remove `GlobalFeatures` and `LocalFeatures` from the codebase

.github/workflows/ci.yml, .github/workflows/publish_master.yml, .github/workflows/publish_release.yml, Directory.Build.props, LICENSE.txt, src/DotNetLightning.Core/DotNetLightning.Core.fsproj, src/Secp256k1.Net/Secp256k1.Net.csproj, tests/EventAggregator.Tests/EventAggregator.Tests.fsproj, tests/Secp256k1.Net.Test/Secp256k1.Net.Test.csproj
See commit message for the detail.
See #80 for a context.
In original discussion, I was planning to create `stable` branch, but it seemed to me that just pushing a new tag is enough for now.
=> Add workflow for Continuous Deployment

.github/workflows/ci.yml
See 
https://github.com/joemphilips/DotNetLightning/pull/89#discussion_r419345201
for the context.
=> run CI in both PR and push

src/DotNetLightning.Core/Channel/Channel.fs
When we are waiting for the `funding_signed` message we already know the true channel id of the channel, rather than just the temporary channel id. As such, we can store the true channel id in `WaitForFundingSignedData`. This fixes a bug in geewallet where querying the channel id of a channel would return the temporary channel id rather than the true channel id.
=> Use correct channel id in WaitForFundingSigned

tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj, tests/DotNetLightning.Core.Tests/PrimitivesTests.fs
Add a test for `FeeRatePerKw.FromFee`.
=> Add test for FeeRatePerKw.FromFee

src/DotNetLightning.Core/Payment/PaymentRequest.fs, tests/DotNetLightning.Core.Tests/PaymentTests.fs
=> Fix bug in payment secret decode

src/DotNetLightning.Core/Channel/Channel.fs, src/DotNetLightning.Core/DotNetLightning.Core.fsproj, src/DotNetLightning.Core/Serialization/LightningStream.fs, tests/DotNetLightning.Core.Tests/KeyRepositoryTests.fs, tests/DotNetLightning.Core.Tests/TransactionTests.fs, tests/DotNetLightning.Core.Tests/TxOutLexicographicCompareTests.fs, tests/EventAggregator.Tests/Sample.fs
This PR fixes the build warnings.
=> Fix build warnings

.github/workflows/ci.yml, README.md, src/DotNetLightning.Core/DotNetLightning.Core.fsproj, tests/DotNetLightning.Core.Tests/Generators/Generators.fs, tests/DotNetLightning.Core.Tests/Generators/Payments.fs, tests/DotNetLightning.Core.Tests/LSATTests.fs, tests/DotNetLightning.Core.Tests/PaymentPropertyTests.fs
* Since Macaroons test has annoying Bug which only occurs in "windows * non-bouncycastle build"
* See https://github.com/joemphilips/DotNetLightning/issues/153
=> Stop publishing Macaroons in non-BouncyCastle build.

src/DotNetLightning.Core/Channel/CommitmentsModule.fs, src/DotNetLightning.Core/Transactions/Transactions.fs
* Core: be 100% sure to not have randomness in TransactionBuilder
* Core/Channel: use deterministic TransactionBuilder
* Use createDeterministicTransactionBuilder in makeCommitTx
=> Tx builder improvements

src/DotNetLightning.Core/Channel/Channel.fs, src/DotNetLightning.Core/Channel/ChannelError.fs, src/DotNetLightning.Core/Channel/ChannelOperations.fs, src/DotNetLightning.Core/Channel/ChannelTypes.fs, src/DotNetLightning.Core/Channel/ChannelValidation.fs, src/DotNetLightning.Core/Channel/Commitments.fs, src/DotNetLightning.Core/Channel/CommitmentsModule.fs, tests/DotNetLightning.Core.Tests/TransactionTests.fs
This builds on top of #170.
Remove duplicated/unused fields to simplify the code.
=> Remove unused fields and events and 

src/DotNetLightning.Core/Channel/Channel.fs, src/DotNetLightning.Core/Channel/ChannelTypes.fs, src/DotNetLightning.Core/Channel/Commitments.fs, src/DotNetLightning.Core/Channel/CommitmentsModule.fs
* Move RemoteNextCommitInfo into the channel state 
* Remove WaitingForRevocation type
* Replace Deferred field of WaitForFundingConfirmedData
=> Move things related to revocation 

src/DotNetLightning.Core/Transactions/Transactions.fs
This function is a duplicate of tryGetFundsFromRemoteCommitmentTx.
=> Transactions: remove makeClaimP2WPKHOutputTx function

src/DotNetLightning.Core/TransactionUtils.fs
These files were not included in the build.
(In fact 2 of them are empty and the 3rd is
incomplete, it doesn't even build).
=> Core: remove dead code

.github/workflows/build+test.yml, .github/workflows/publish.yml, src/DotNetLightning.Core/Utils/LNMoney.fs, src/TaskUtils/TaskUtils.fsproj, tests/AEZ.Tests/AEZ.Tests.csproj, tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj, tests/Macaroons.Tests/Macaroons.Tests.csproj
=> some package cleanups.

src/DotNetLightning.ClnRpc/DotNetLightning.ClnRpc.fsproj, tests/DotNetLightning.ClnRpc.Tests/DotNetLightning.ClnRpc.Tests.fsproj
with this and commit: 2d384fbffcf6b7b131f159209bbf5a529e1363c6
Now DNL.ClnRpc includes all necessary dll's into the package.
unfortunately (probably) this was the easiest way to do it.
=> Include every necessary packages into DNL.ClnRpc     

src/DotNetLightning.ClnRpc/DotNetLightning.ClnRpc.fsproj
This reverts commit 197bd2311d247e50113886f18cdfcb327f792a06.
=> Revert "remove PrivateAssets=All from DNL.ClnRpc.fsproj"

Directory.Build.props, src/DotNetLightning.Core/Payment/PaymentRequest.fs, tests/DotNetLightning.Core.Tests/PaymentTests.fs
This commit adds support for creating LTC invocies.
=> Core: add LTC network prefixes

examples/HelloWorldPlugin/HelloWorldPlugin.cs, examples/HelloWorldPlugin/PluginLoggerExtensions.cs, examples/HelloWorldPlugin/Program.cs, src/DotNetLightning.ClnRpc/Plugin/PluginServerBase.fs, tests/DotNetLightning.ClnRpc.Tests/Helpers.fs, tests/DotNetLightning.ClnRpc.Tests/Tests.fs
`WithCancellation` on server start up must work
As an fail-safe for the case c-lightning never responds.
without this, the plugin might be a zombie process.
=> add test for ClnRpc closes correctly

src/DotNetLightning.ClnRpc/Plugin/PluginServerBase.fs, src/DotNetLightning.ClnRpc/Requests.fs, tests/DotNetLightning.ClnRpc.Tests/Tests.fs
=> Fix 20220731

src/DotNetLightning.ClnRpc/Primitives.fs
When UInt64.MaxValue has been returned from rpc,
we convert it to Int64.MaxValue, so that it won't
throw error when parsing json.
=> ClnRpc: Update msat parsing

src/DotNetLightning.ClnRpc/Primitives.fs
The change is self explanatory.
=> fix miner bug in parseClnAmount

src/DotNetLightning.Core/Channel/Channel.fs, src/DotNetLightning.Core/Utils/LNMoney.fs, tests/DotNetLightning.Core.Tests/ChannelTests.fs, tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj
This function returns the spendable balance of the channel
(excluding fees and channel reserve).
=> Core: add SpendableBalance function

Directory.Build.props
based on: https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link
=> Add sourcelink for better debugging experience.

src/DotNetLightning.Core/Serialization/Msgs/Msgs.fs, tests/DNLTestBase/Generators/Msgs.fs, tests/DotNetLightning.Core.Tests/Serialization.fs
DNS hostname type has been added to node_announcement msg.
This commit supports is serialization.
=> Add DnsHostname type to NetAddress
