joemphilips/DotNetLightning

.github/workflows/ci.yml

Just using the git hash could not be enough for proper version
sorting (last version pushed to nuget should be the first one to
be listed in the nuget website).
We also shorten the githash to not surpass the length limit of the
version string (7 is the default short git hash length, see:
https://stackoverflow.com/a/18134919/544947).

githubActions: improve versioning

---

.github/workflows/ci.yml
README.md
src/DotNetLightning.Core/DotNetLightning.Core.fsproj
src/DotNetLightning.Core/Serialize/LightningStream.fs
src/DotNetLightning.Core/Transactions/Transactions.fs

This way DotNetLightning can be consumed by platforms
different than .NETCore (e.g. Xamarin frontends, Mono...).

.NETStandard for the Core lib/nuget

---

.github/workflows/ci.yml

(Also use the official installation way via `apt` instead of `dpkg`.)

ci: update .NETCore 3.0 version from preview9 to final

---

.github/workflows/ci.yml
README.md
src/DotNetLightning.Core/Chain/KeysInterface.fs
src/DotNetLightning.Core/Crypto/CryptoUtils.fs
src/DotNetLightning.Core/Crypto/Generators.fs
src/DotNetLightning.Core/Crypto/Sphinx.fs
src/DotNetLightning.Core/Crypto/StreamCipherStream.fs
src/DotNetLightning.Core/DotNetLightning.Core.fsproj
src/DotNetLightning.Core/LN/Channel.fs
src/DotNetLightning.Core/LN/CommitmentsModule.fs
src/DotNetLightning.Core/LN/PeerChannelEncryptor.fs
tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj
tests/DotNetLightning.Core.Tests/EncryptDecrypt.fs
tests/DotNetLightning.Core.Tests/GeneratorsTests.fs
tests/DotNetLightning.Core.Tests/TransactionBolt3TestVectorTests.fs
tests/DotNetLightning.Infrastructure.Tests/DotNetLightning.Infrastructure.Tests.fsproj

Hi Joe,
As the PR title mentions, this allows for using BouncyCastle instead of Secp256k1 and NSec. There are tests for the NSec replacement parts.
If you accept this, I can add you as an owner of the DotNetLightning package on nuget, you would have to create a new API key that can upload both packages (not just one).
Let me know what you think!

Opt-in (non-default) BouncyCastle support

---

.github/workflows/ci.yml
tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj

<s>Before this commit, we would run all steps unconditonally.</s> EDIT: Not true, I was mistaken. But we would publish BouncyCastle before seeing if Infrastructure builds and passes the test.
Since the native test run is running Infrastructure tests that
are not run in the first go, we wait with publishing the Bouncy-
Castle variant until the native tests have run.

CI: Only publish if tests pass on both build variants

---

src/DotNetLightning.Core/Transactions/CommitmentSpec.fs

Because `CommitmentSpec` contains a member without arguments, NewtonSoft.Json can't serialize it. So I need to make a custom POD record that contains all its data. But I can't do that, since the record is internal. This makes it public, which makes me able to serialize the channel state.

Core: Make CommitmentSpec public

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelCommands.fs
src/DotNetLightning.Core/Channel/ChannelTypes.fs

Let's say we restored the channel state from disk after
a long wait for the confirmation of the funding transaction.
In this situation, we need to reestablish, and the message
to reply with is trivial since nothing has been revoked yet.

Reestablishment while waiting for funding tx confs

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelCommands.fs

When we are the funder, the counterparty determines the
MinimumDepth that the funding transaction should reach
before funding_locked.
Instead of incorrectly waiting for the limit that has been
configured in ChannelHandshakeConfig (which should be used
only for inbound channels) use the number from accept_channel,
which is now saved in RemoteParams.
Fixes #38

Use MinimumDepth from AcceptChannel message

---

src/DotNetLightning.Core/Peer/Peer.fs
src/DotNetLightning.Core/Peer/PeerChannelEncryptor.fs
src/DotNetLightning.Infrastructure/PeerManager.fs
tests/DotNetLightning.Core.Tests/PeerChannelEncryptorTests.fs

Before this commit, a random key would be generated, which is not useful
outside testing, since users will usually reuse the same transport
encryption key for both outbound and inbound connections.
By making CreateOutbound take an explicit key, consumers of this
function can explicitly generate a key if they so desire.
Consumers in Infrastructure have been modified to now generate a key
themselves, retaining previous behaviour.

Make CreateOutbound take an explicit private key

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelTypes.fs

Before, we could only generate a channel_establish message if we
received one. Obviously, not every node can work like this.
Furthermore, since we weren't really validating the incoming
message anyway, there was no added benefit to requiring it.
This commit makes it possible to generate a channel_reestablish
message in all states, not just when we are waiting for the funding
transaction to confirm. For example, we need to generate the
message in the Normal state very often.

Flexible ChannelReestablish

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelCommands.fs
src/DotNetLightning.Core/Channel/ChannelTypes.fs
src/DotNetLightning.Infrastructure/PeerManager.fs

This fixed version properly replaces ApplyChannelReestablished with
CreateChannelReestablish, which fixes one test, and adds a noop
handler in another test. Tests now pass.

Flexible ChannelReestablish (fixed)

---

src/DotNetLightning.Core/DotNetLightning.Core.fsproj
src/DotNetLightning.Core/Serialize/Features.fs
src/DotNetLightning.Core/Utils/Extensions.fs
tests/DotNetLightning.Core.Tests/Serialization.fs

Looks like the bolt has stopped using notion of "local/global" feature and now it uses one single `feature` to serve both purpose. See [this evil PR for the detail](https://github.com/lightningnetwork/lightning-rfc/pull/666)
So I follow [what eclair did](https://github.com/ACINQ/eclair/commit/72338ab58dea649018cbf6af4344295b104ba211) to make things simple.
My next step is to remove `LocalFeatures` and `GlobalFeatures` from the codebase altogether.

Prepare new type `Feature` to represent featurebits

---

src/Secp256k1.Net/Interop.cs
src/Secp256k1.Net/Secp256k1.cs

The bindings to the native library functions were incorrectly using C# `uint` in place of C's `size_t`. This was causing the library to segfault on 64bit linux due to C#'s `uint` being 32bit whereas C's `size_t` is 64bit.
This PR changes these bindings to use `UIntPtr` as a closer approximation of `size_t`.

Fix Secp256k1 on 64bit Linux

---

Directory.Build.props
src/DotNetLightning.Core/DotNetLightning.Core.fsproj
src/DotNetLightning.Core/Routing/Graph.fs
src/DotNetLightning.Core/Routing/Router.fs

depends on #66 
I want to turn on a flag for deterministic build and unused variable warning at solution-wide. This kind of modification should be done at an early phase as possible.
This change will cause much more bloated warning message (mostly for unused variables in Infrastructure) at some point I will deal with them all and turn on `warnaserror` flag.

Prepare directory build file

---

tests/DotNetLightning.Infrastructure.Tests/Constants.fs

The test suite's `ProvideFundingTx` function would randomly (50% of the time) return an incorrect funding output index. This is because NBitcoin was shuffling the funding tx's txouts, but the function would always return an output index of 0.
This fixes the problem by making `ProvideFundingTx` disable txout shuffling on the transaction builder and making it always return an output index of 1.

Fix dummy funding tx generation

---

src/DotNetLightning.Core/Serialize/Features.fs

`FeatureBit.PrettyPrint` throws an exception when I use it to print the features sent by a remote peer. This fixes the issue.

Fix IndexOutOfRange Exception in FeatureBit.PrettyPrint

---

src/DotNetLightning.Core/Channel/CommitmentsModule.fs

Prior to this change, any changes that were made to the commitment transactions would get dropped since the channel state would never switch over to the newly signed commitment.

Update to new spec when sending/receiving a commitment.

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/Commitments.fs
src/DotNetLightning.Core/Channel/CommitmentsModule.fs

Replace the use of `Choice1Of2` for storing the next remote commit info with a new discriminated union type which has two variants. I found that this makes the code a lot clearer and easier to understand.

Add RemoteNextCommitInfo type

---

src/DotNetLightning.Core/Serialize/Msgs/Msgs.fs

Some lightning implementations will send non-printable data in error messages. For instance outdated versions of lnd will do this:
https://github.com/lightningnetwork/lnd/commit/ff37b711c6dea62f6acb9d0aaca36417edcda820
Where these are the error codes (sent as single-byte error messages):
https://github.com/lightningnetwork/lnd/blob/9b1ecbd3fa3fd93a6d95a5f71921c73777340760/lnwire/error.go#L12
These errors need to be printed as bytes when displayed to the user, rather than interpreted as strings. Error.GetFailureMsgData will now checks whether an error message is printable before returning the message as a string and, if it's not, returns a string containing the hex-encoded binary data in the error.

Make GetFailureMsgData format non-printable error messages

---

src/DotNetLightning.Core/Serialize/Msgs/Msgs.fs
src/DotNetLightning.Core/Utils/Extensions.fs

The `global_features` and `local_features` fields of the init msg need to be ORed together to create the complete feature set. Previously they were being concatenated, resulting in an invalid feature set.

Fix feature set calculation when deserializing init msg

---

.github/workflows/ci.yml
src/DotNetLightning.Core/Serialize/Msgs/Msgs.fs
tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj
tests/DotNetLightning.Infrastructure.Tests/DotNetLightning.Infrastructure.Tests.fsproj

Running expecto with `dotnet test` worked before, but it has been ignoring all tests when we run with `dotnet test`
This is caused by version mismatch between `YoloDev.Expecto.TestSdk` and `Expecto` itself, When I change Expecto version to `"*"` , it worked fine.
We were using version `8.*` of expecto, and YoloDev.Expecto.TestSdk were using Expecto version `9.*` internally... And that caused this behavior.
There are many solutions to this, but I guess I should instead just run tests by `dotnet run` , that sounds more simpler in many ways.

use dotnet run to run expecto tests

---

src/DotNetLightning.Core/Payment/PaymentRequest.fs
src/DotNetLightning.Core/Serialize/Features.fs
src/DotNetLightning.Core/Serialize/Msgs/Msgs.fs
src/DotNetLightning.Core/Utils/Extensions.fs
tests/DotNetLightning.Core.Tests/PaymentTests.fs
tests/DotNetLightning.Core.Tests/Serialization.fs

The PR makes init message serialization give special treatment to the `var_onion_optin` feature flag. This flag (if it is present) will only be placed in the `global_features` section of the init message while other flags are only placed in the `local_features` section. This makes use compatible with legacy clients that distinguish between global and local features since `var_onion_optin` was the only global feature in the spec before the spec was changed and the two feature sets were merged.
Some other miscellaneous changes are:
I added `SetFeatureFlag` and `GetFeatureFlag` methods to the `FeatureBit` type since this made it more convenient to implement `Init.Serialize`.
I've removed the lazily-initialized `mutable bytes` field from `FeatureBit` since this made it possible for …

Init message legacy compatibility

---

src/DotNetLightning.Core/Channel/ChannelError.fs

The function `checkDustLimitIsLargerThanOurChannelReserve` was calculating the channel reserve based on the funding amount of the` open_channel` message, rather than using the channel reserve that was actually sent in the `open_channel` message.
This fixes the bug.

Fix bug in accept_channel msg validation

---

src/DotNetLightning.Core/Channel/ChannelError.fs
src/DotNetLightning.Core/Channel/ChannelValidation.fs

The `OpenChannelMsgValidation.checkRemoteFee` method rejects any `open_channel` message with a fee rate less than the estimated fee rate. This PR changes it to use the provided `MaxFeeRateMismatchRatio` config option.

Use MaxFeeRateMismatchRatio in checkRemoteFee

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelError.fs
src/DotNetLightning.Core/Channel/ChannelValidation.fs

This builds off of #95 and can be rebased if any further changes occur on that PR.
This PR adds validation to the `CreateOutbound` channel command which enforces that the channel parameters are sensible - ie. that the channel wouldn't be rejected by any sane and spec-compliant peer.
It also removes the (unused) `checkIfFundersAmountSufficient` function and moves one of it's checks into a new `checkFunderCanAffordFee` function. The other two checks were unnecessary and overly restrictive. One of them checked that `push_msat` is greater than the fundee's `channel_reserve`, which is unlikely to ever be the case. The other checked that the funder's initial channel balance minus their channel reserve is enough to cover commitment tx fees. This is also unnecessary since a channel is closed when …

Outgoing open channel validation

---

src/DotNetLightning.Core/Channel/ChannelError.fs
src/DotNetLightning.Core/Channel/ChannelValidation.fs
src/DotNetLightning.Core/Crypto/CryptoUtils.fs
src/DotNetLightning.Core/Peer/PeerError.fs
src/DotNetLightning.Core/Serialize/Features.fs
src/DotNetLightning.Core/Serialize/Msgs/Msgs.fs
src/DotNetLightning.Core/Transactions/TransactionError.fs

Add a `Message` member to error types which returns an error message suitable for displaying to the user, in contrast with `ToString` which returns a debugging-friendly textual representation of the error object.
This MR also expands on and attempts to improve some of the existing error messages.

Add Message member to error types

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelTypes.fs

* When closing mutually, The API consumer had to get FinalizedTx through
ClosingData.FinalizedTx.
But this is not straightforward, ideally the returned ChannelEvents
must hold the object to perform side-effects directly.
So add txToPublish field in MutualClosePerformed event.
* Also, make the state simpler by holding only one `FinalizedTx` in
`ClosingData` This is because I could not imagine the case
that the node wants to broadcast more than one mutually-agreed
closing tx.

Make explicit that tx must be broadcasted.

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelError.fs
src/DotNetLightning.Core/Transactions/Transactions.fs
src/DotNetLightning.Core/Utils/Primitives.fs

Before this commit, the channel was calculating the fee
with its virtual size instead of what it supposed to give
to `FeeRatePerKw.ToFee`, that is a number of weight unit
for the tx which is 4 times larger than virtual size.
This commit fixes the issue by changing the method name
for the `FeeRatePerKw` to those more explicit.

Fix bug in fee calculation for first closing fee.

---

src/DotNetLightning.Core/Channel/ChannelError.fs

It was very ambiguous to have a "Msg" member in an error type that
actually doesn't contain the error message, so we rename this to
"NetworkMsg".

Core: add "Network" prefix to "Msg" member of error types

---

src/DotNetLightning.Server/DotNetLightning.Server.fsproj
tests/DotNetLightning.Integration.Tests/DotNetLightning.Integration.Tests.csproj

When opening the solution with VS4Mac, it was giving this error right away:
```
Detected package downgrade: FSharp.Core from 4.7.0 to 4.5.2. Reference the package directly from the project to select a different version.
DotNetLightning.Integration.Tests -> DotNetLightning.Server -> DotNetLightning.Core -> FSharp.Core (>= 4.7.0)
DotNetLightning.Integration.Tests -> DotNetLightning.Server -> FSharp.Core (>= 4.5.2)
Detected package downgrade: FSharp.Core from 4.7.0 to 4.5.2. Reference the package directly from the project to select a different version.
DotNetLightning.Integration.Tests -> DotNetLightning.Server -> TaskUtils -> ResultUtils -> FSharp.Core (>= 4.7.0)
DotNetLightning.Integration.Tests -> DotNetLightning.Server -> FSharp.Core (>= 4.5.2)
Restore failed.
```

Fix package restore with VS4Mac

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Crypto/RevocationSet.fs
src/DotNetLightning.Core/Serialize/LightningStream.fs
src/DotNetLightning.Core/Serialize/Msgs/Msgs.fs
src/DotNetLightning.Core/Utils/Primitives.fs
tests/DotNetLightning.Core.Tests/Generators/Msgs.fs
tests/DotNetLightning.Core.Tests/Generators/Primitives.fs
tests/DotNetLightning.Core.Tests/Serialization.fs

This PR adds the ability to convert a `RevocationSet` to/from a list of `CommitmentNumber * RevocationKey`. This is useful for being able to serialize a `RevocationSet`.
It also removes the hard-coded values from the `makeChannelReestablish` and uses the keys and commitment numbers from the `Commitments` object instead.

More revocation fixes

---

src/DotNetLightning.Core/Utils/Primitives.fs
tests/DotNetLightning.Core.Tests/TransactionBolt3TestVectorTests.fs

Obscured commitment numbers treat the commitment number as counting upwards from 0 rather than downwards from `UInt48.MaxValue`.
This hadn't shown up in testing so far since we were only testing against ourselves and so the error cancelled out on both sides.

Fix ObscuredCommitmentNumber generation

---

src/DotNetLightning.Core/Channel/ChannelTypes.fs

The ClosingData type was CLIMutable to allow for json
serialization and deserialization.
However, that only avoided an exception being thrown.
The data was lost when writing and reading the json.
This commit removes the CLIMutable attribute and
makes the type public as the other types.

Make ClosingData public instead of CLIMutable

---

src/DotNetLightning.Core/Channel/Channel.fs

The commitment points we send in the `channel_reestablish` messages are wrong. We need to send our commitment point for the peer's most recent commitment, not their point. This commit fixes the issue.

Send correct commitment point in channel_reestablish messages

---

.github/workflows/ci.yml
src/DotNetLightning.Core/Payment/PaymentRequest.fs
src/DotNetLightning.Core/Serialize/Features.fs
src/DotNetLightning.Core/Serialize/TLVs.fs

This allows for compiling on Mono, which still ships with F# 4.5.

Avoid newer F# syntax

---

src/DotNetLightning.Core/Serialize/Msgs/Msgs.fs
src/DotNetLightning.Core/Serialize/TLVs.fs
tests/DotNetLightning.Core.Tests/Serialization.fs

This is a fix for changes introduced in https://github.com/joemphilips/DotNetLightning/pull/118 which caused chain hashes to get serialized in reverse order.
This allows DNL to open channels with lnd again.

Fix chain hashes being serialized in reverse

---

Directory.Build.props
src/DotNetLightning.Core/Transactions/Transactions.fs

(Based on PR[1] from Andrew Cann.)
The lightning spec decrees that the closing tx's outputs need to be in
lexicographical order. Instead, they were ending up in the wrong order
thanks to (a) not being added in the correct order and (b)
`TransactionBuilder` shuffling them anyway when calling
`BuildTransaction`.
`makeClosingTx` now uses an explicit order and we disable shuffling
inputs and outputs for all transactionBuilders (this feature was
introduced in NBitcoin 5.0.54 [2] so an upgrade to this version is
included).
(As an extra improvement, this commit also renames 'n' to 'network',
and creates a constant for 0xffffffffu.)
Fixes https://github.com/joemphilips/DotNetLightning/issues/131
[1] https://github.com/joemphilips/DotNetLightning/pull/132
[2] …

Fix closing tx output-reordering bug

---

src/DotNetLightning.Core/Transactions/Transactions.fs

NBitcoin's `TransactionBuilder.ShuffleOutputs` flag is broken and gets ignored when building the `Transaction`. This can be worked around by setting the `TransactionBuilder`'s `RandomShuffle` field to `null`, which disables all random shuffling.
This fix can be removed once NBitcoin bug #931 is fixed:
See:
https://github.com/MetacoSA/NBitcoin/issues/931

Workaround NBitcoin txout shuffling bug

---

src/DotNetLightning.Core/Transactions/Transactions.fs
src/DotNetLightning.Core/Utils/NBitcoinExtensions.fs
tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj
tests/DotNetLightning.Core.Tests/TxOutLexicographicCompareTests.fs

Ordering txouts by their byte representation doesn't give a valid lexicographic ordering due to (a) the amount being represented in little-endian (BIP69 requires that txouts with smaller values appear first) and (b) F#'s comparision function on byte arrays always ordering smaller arrays first (eg.` [| 1 |]` < `[| 0; 0 |]` < `[| 1; 1 |]`), rather than ordering them in dictionary order (ie.` [| 0; 0 |]` < `[| 1 |]` < `[| 1; 1 |]`).
This commit adds a `TxOut.LexicographicCompare` method which correctly implements BIP69's txout lexicographic ordering spec. This is then used for ordering outputs in the closing transaction.

Add TxOut.LexicographicCompare method

---

Directory.Build.props
src/DotNetLightning.Core/Transactions/Transactions.fs

To pick up this bugfix:
https://github.com/MetacoSA/NBitcoin/commit/96b1eb76b42f5f833072d13096aea9418e5ff475
And so that we can revert this workaround:
"Workaround NBitcoin txout shuffling bug"
(d813a979b50c4966d2cdd8902228bcf135a6d8a0)

Bump NBitcoin to 5.0.65

---

src/DotNetLightning.Core/Utils/Primitives.fs

FeeRatePerKw.FromFee was mis-calculating the fee rate from the fee and weight.
By @canndrew

Fix fee rate calculation

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelOperations.fs
src/DotNetLightning.Core/Channel/ChannelTypes.fs

For some of the work we're doing on geewallet it became problematic for us to have to pass in a `ProvideFundingTx` when initially creating a `Channel`.
This commit changes things so that when creating a channel, instead of passing DNL a closure which takes the funding tx parameters and returns the funding tx, DNL will now returns the funding tx parameters and requires us to pass it the funding tx using a new `CreateFundingTx` command.
This is also has the extra type-safety advantage of us not having to pass DNL a dummy `ProvideFundingTx` (which just calls `failwith`) when creating an inbound channel.

Replace ProvideFundingTx with WaitForFundingTx state

---

Directory.Build.props
src/DotNetLightning.Core/Channel/CommitmentToLocalExtension.fs
src/DotNetLightning.Core/Channel/CommitmentsModule.fs
src/DotNetLightning.Core/DotNetLightning.Core.fsproj
src/DotNetLightning.Core/Utils/Keys.fs
src/DotNetLightning.Core/Utils/SeqParser.fs
src/ResultUtils/OptionCE.fs
src/ResultUtils/ResultUtils.fsproj
tests/DotNetLightning.Core.Tests/CommitmentToLocalExtensionTests.fs
tests/DotNetLightning.Core.Tests/DotNetLightning.Core.Tests.fsproj
tests/DotNetLightning.Core.Tests/TransactionTests.fs

This PR adds support for force-closing channels.
In order to support this, this PR adds three things:
1) `CommitmentToLocalExtension`
This is an `NBitcoin` `BuilderExtension` that tells `NBitcoin.TransactionBuilder` how to recognize and sign `to_local` txouts from lightning commitment transactions. This is needed for force-closing to spend `to_local` outputs.
2) `tryGetFundsFromLocalCommitmentTx`
When force-closing a channel this function is used to recover funds from our commitment transaction. It returns a `TransactionBuilder` which is used to generate a recovery transaction which can be broadcast once the timelock on the `to_local` output has expired.
3) Two new computation expressions
`OptionCE` is a computation expression for creating options, similar to the result computation …

Add support for force-closing channels

---

src/DotNetLightning.Core/Channel/CommitmentsModule.fs
tests/DotNetLightning.Core.Tests/TransactionTests.fs

This PR adds a `tryGetFundsFromRemoteCommitmentTx` function, similar to `tryGetFundsFromLocalCommitmentTx` except that it recovers funds from a remote commitment tx. Currently, it only redeems the `to_remote` output of the commitment tx, ie. it doesn't implement revocation. However a future PR will expand this function to also redeem to `to_local` output when we have the remote's per-commitment-secret for the commitment tx.
This also expands the test for `tryGetFundsFromLocalCommitmentTx` to test both functions, since they re-use the same setup.

Support retrieving funds from remotely force-closed channels

---

.github/workflows/ci.yml
.github/workflows/publish_master.yml
.github/workflows/publish_release.yml

Version 20.04 is also LTS, and not as old as 18.04.
(Sorry, I know this sounds like upgrading for the sake of upgrading,
but there's no point in supporting a 3 year old OS, IMO.)

CI: upgrade Ubuntu 18.04 to 20.04

---

src/DotNetLightning.Core/Channel/CommitmentToLocalExtension.fs
src/DotNetLightning.Core/Channel/CommitmentsModule.fs
src/DotNetLightning.Core/Transactions/Transactions.fs
tests/DotNetLightning.Core.Tests/TransactionTests.fs

This PR adds support for generating penalty transactions. The included changes are:
* `CommitmentToLocalExtension` has been extended to support spending from revoked `to_local` outputs of a remote's commitment tx.
* A new `createPenaltyTx` function has been added to the `ForceCloseFundsRecovery` module which claims both the `to_remote` and `to_local` outputs of a commitment tx, given the per-commitment-secret.
* The fund-recovery test has been extended to test `createPenaltyTx`.

Penalty transactions

---

src/DotNetLightning.Core/Crypto/CryptoUtils.fs

The function `BouncyCastleSecp256k1.tweakKey` would return a bogus result if the tweaked key contained leading zero bytes. This is because it would first convert the result from a `BigInteger` to an array, truncating any leading zero bytes, then write the array to the target `Span<byte>`, ignoring the possibility that the array is too small due to truncated bytes.
This PR fixes the issue by writing the resulting array to the correct offset into the span and zeroing the head of the span.

Fix key-tweaking bug in BouncySecp256k1

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelTypes.fs
src/DotNetLightning.Core/Channel/CommitmentsModule.fs

Applying an `update_fee` message would cause DNL to validate the message but not actually apply it to its commitments.
It now updates its commitments as it should.

Apply update fee messages

---

src/DotNetLightning.Core/Channel/ChannelError.fs
src/DotNetLightning.Core/Channel/CommitmentsModule.fs
src/DotNetLightning.Core/Utils/Primitives.fs

Move/publicize ChannelError.feeRateMismatch and ForceCloseFundsRecovery.tryGetObscuredCommitmentNumber
These two functions are useful outside of DotNetLightning.

Make two functions public

---

src/DotNetLightning.Core/DotNetLightning.Core.fsproj

Somehow, the "ResolveReferences" target was not found anymore by
the msbuild tool used in this lane, but we don't need this target
when using Mono because this workaround is only used when using
"dotnet" to create the nuget package.

Fix "build_with_fsharp_from_mono" CI lane

---

src/DotNetLightning.Core/Channel/Commitments.fs
src/DotNetLightning.Core/Channel/CommitmentsModule.fs

Currently, we need to use a couple of internal functions to
calculate commitment outpoints amounts so we want to have this
to not only make a public API for this but also simplify it and
reduce the amount of duplicated code
We use this to calculate the exact amount of toRemote and toLocal
output to then be able to calculate the watch tower reward based
on that.

Core/Channel: function to calc outpoints of commitTx

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelError.fs
src/DotNetLightning.Core/Channel/ChannelOperations.fs
src/DotNetLightning.Core/Channel/ChannelTypes.fs
src/DotNetLightning.Core/Channel/ChannelValidation.fs
src/DotNetLightning.Core/Channel/CommitmentsModule.fs
src/DotNetLightning.Core/Utils/Config.fs
tests/DotNetLightning.Core.Tests/TransactionTests.fs

This PR removes the pre-channel-establishment states from `ChannelState`, factoring them into their own types.
In the current design of DNL there is a type `Channel` which contains an interior `ChannelState`, and we perform operations on channels by calling `executeCommand` with a `ChannelCommand`. Some of these states only represent channels prior to channel establishment.  These states only support a single `ChannelCommand` and it's nonsense to either use a different command or to use that command when the channel is in a different state.
For instance, if we have a channel in the `WaitForAcceptChannel` state then the only command we can perform is `ApplyAcceptChannel` when we receive the corresponding `accept_channel` message. It doesn't make sense to attempt to (for example) close a …

Remove pre-channel states

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Serialization/Msgs/Msgs.fs
src/DotNetLightning.Core/Serialization/TLVs.fs
tests/DotNetLightning.Core.Tests/Generators/Msgs.fs
tests/DotNetLightning.Core.Tests/Serialization.fs

For more recent versions of the lightning spec open/accept channel messages now use a tlv stream at the end of the message to indicate the presence of an upfront shutdown script. This turns out to be backwards-compatible, in that the on-the-wire format turns out to be identical.
If `option_upfront_shutdown_script` was advertised by both parties, then the shutdown script field/TLV is mandatory (but may be length `0` to indicate no shutdown script), otherwise the field is optional (but still allowed to be present). As such, it seems simpler and more bug-proof to always include the field and to set it to a length-`0` script if we don't have a shutdown script. Hence the changes to the test.

Update message formats for open/accept channel

---

src/DotNetLightning.Core/Channel/ChannelTypes.fs

The types `WaitForOpenChannelData`, `WaitForFundingInternalData`, and `WaitForRemotePublishFutureCommitmentData` were defined but not used at all. They have been removed.

Remove unused types from ChannelTypes module

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelTypes.fs

According to lightning spec, if the receiver agrees with
the fee, it should reply with a closing_signed with the
same fee_satoshis value so to transport this message we
need to pass it inside MutualClosePerformed event,
to be transported to the other peer.
Source:
https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#requirements-6

Core: return peer's closing_signed msg if accepted

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelOperations.fs
src/DotNetLightning.Core/Serialization/LightningStream.fs
src/DotNetLightning.Core/Serialization/Msgs/Msgs.fs
src/DotNetLightning.Core/Serialization/TLVs.fs
src/DotNetLightning.Core/Transactions/Scripts.fs
src/DotNetLightning.Core/Transactions/Transactions.fs
src/DotNetLightning.Core/Utils/Config.fs
src/DotNetLightning.Core/Utils/Primitives.fs
tests/DotNetLightning.Core.Tests/Generators/Msgs.fs
tests/DotNetLightning.Core.Tests/Generators/Primitives.fs
tests/DotNetLightning.Core.Tests/Serialization.fs
tests/DotNetLightning.Core.Tests/TransactionTests.fs

This builds off of the previous PR here: https://github.com/joemphilips/DotNetLightning/pull/164
Previously the local shutdown script was stored in two places in the channel and also provided as an argument when initiating a shutdown.  This made it possible to send invalid shutdown messages if the shutdown scripts provided by the user at different times were different. Also, shutdown scripts have to be in certain forms, but the only place that they were validated was when initiating a shutdown.
There's now a `ShutdownScriptPubKey` type which wraps a `Script` and enforces that the script is a valid shutdown script. This is used throughout the code for all scripts which are shutdown scripts, which forces us to check their validity at all required points.
The `DefaultFinalScriptPubKey` field …

Refactor shutdown scripts

---

src/DotNetLightning.Core/Channel/Channel.fs
src/DotNetLightning.Core/Channel/ChannelTypes.fs
src/DotNetLightning.Core/Channel/ChannelValidation.fs
src/DotNetLightning.Core/Channel/Commitments.fs
src/DotNetLightning.Core/Channel/CommitmentsModule.fs

Since all ChannelState variants have a Commitments field, this field can
be factored out into the Channel object.
Also, remove the ChannelId field from the ChannelState variants since it
is duplicated inside Commitments, formats the code to remove
remove long lines and excessive rightward drift and make
Commitments.ChannelId a method instead of a field.

Moving commitments into the Channel type

---

src/DotNetLightning.Core/Channel/CommitmentToLocalExtension.fs

This commit implements the function "EstimateScriptSigSize"
which helps NBitcoin with estimating fees for transactions that
spend the to_local output of a commitment tx, transactions that
use this output are "penalty tx" and transaction that recovers the funds
from local commitment tx (created by tryGetFundsFromLocalCommitmentTx
function).
Reference for ECDSA signature size:
https://github.com/bitcoin/bips/blob/master/bip-0137.mediawiki#background-on-ecdsa-signatures

Channel: fix fees estimation for some transactions

---

src/DotNetLightning.Core/Channel/ChannelConstants.fs
src/DotNetLightning.Core/Channel/ChannelError.fs
src/DotNetLightning.Core/Channel/ChannelValidation.fs
src/DotNetLightning.Core/Utils/Config.fs

Maximum to_self_delay should be customizable to account for currencies
with different block time (e.g. LTC).
This commit moves MaxToSelfDelay to the ChannelHandshakeLimits record.

Core: make maximum to_self_delay customizable

---

src/DotNetLightning.Core/Peer/Peer.fs

Member peerId in type `Peer` was unused.

Core: remove unused member peerId

---

.github/workflows/publish_master.yml
.github/workflows/publish_release.yml

This is useful so that if people fork the project and push to it, they
don't get failed CI runs.
Technique taken from
https://stackoverflow.com/questions/70249519/how-to-check-if-a-secret-variable-is-empty-in-if-conditional-github-actions

GitHubCI: only run publish if Nuget API key is defined as repo secret

---

src/Macaroons/Macaroons.csproj
src/NSec/Cryptography/NSec.Cryptography.csproj

The compiler were warning in non-Portability build
that it has a version mismatch in `System.Runtime.CompilerServices.Unsafe`
This happens only in netstandard2.0 and not in 2.1.
This seems to be the similar issue to https://github.com/dotnet/runtime/issues/46082
that `System.Memory` in netstandard2.0 has a transitive dependency to
`System.Runtime.CompilerServices.Unsafe`.
So fix it by adding Unsafe explicitly in projects using it, as suggested
in the issue above.

Fix compile warning on non-portability build.

---

src/DotNetLightning.Core/Channel/ChannelHelpers.fs

Local commitment txs use RemoteParams.ToSelfDelay,
using LocalParams.ToSelfDelay when searching for outputs
can cause problem if:
LocalParams.ToSelfDelay <> RemoteParams.ToSelfDelay

Core: fix bug in local force close handling

---

src/DotNetLightning.ClnRpc/DotNetLightning.ClnRpc.fsproj

Not sure why, but consuming project can not use DNL included in
DNL.ClnRpc, hopefully this will fix it.

remove PrivateAssets=All from DNL.ClnRpc.fsproj

---

src/DotNetLightning.ClnRpc/Plugin/PluginServerBase.fs

When we use `OptionalArgumentValue` attribute in `PluginServerBase.StartAsync`
method, it will throw `InvalidProgramException` , probably because
method overloading pattern does not comply with that CLR requires.
So stop using.

clnrpc: stop using OptionalParameter in StartAsync

---

src/DotNetLightning.Core/Utils/Primitives.fs

In recent commit to adjust formatting [1], an #if clause was removed,
resulting in applying the `[<Struct>]` attrib always. This is a fantomas
bug which I just reported here [2], but if we reduce circular type
dependencies here, we can just workaround it for now.
[1] https://github.com/joemphilips/DotNetLightning/commit/c0747c951a5b9cfd94180102346ae3419b00f57a
[2] https://github.com/fsprojects/fantomas/issues/2361

Core/Primitives: less circular type deps to workaround fantomas bug

---

src/DotNetLightning.ClnRpc/Plugin/PluginServerBase.fs

Without `Task.Yield` on initializationTask,
the startup process might hang.

fix bug in StartAsync

---

src/DotNetLightning.ClnRpc/Client.fs

Since without inheriting Exception type, it does
not show any error message.

nit: refactor CLightningRPCException

---

examples/HelloWorldPlugin/HelloWorldPlugin.cs
examples/HelloWorldPlugin/PluginLogger.cs
examples/HelloWorldPlugin/Program.cs
src/DotNetLightning.ClnRpc/Plugin/PluginServerBase.fs

Cln Plugin must never write to stdout concurrently, otherwise its
message will be corrupted.
Before this commit, `PluginServerBase` were using
`AsyncSemaphore` to ensure the thread safety for stdout.
This is hard to understand, especially when an user side and a
DNL side both tries to get lock (e.g. for `SendNotification`) and
cause deadlock.
This commit simplifies it by just using `Stream.Synchronized`
to assure the thread safety.

simplify PluginServerBase thread safety

---

src/DotNetLightning.ClnRpc/Client.fs
src/DotNetLightning.ClnRpc/DotNetLightning.ClnRpc.fsproj
src/DotNetLightning.ClnRpc/NewtonsoftJsonConverters.fs
src/DotNetLightning.ClnRpc/Plugin/PluginServerBase.fs
src/DotNetLightning.ClnRpc/Requests.fs
src/DotNetLightning.ClnRpc/SystemTextJsonConverters.fs
tests/DotNetLightning.ClnRpc.Tests/Helpers.fs
tests/DotNetLightning.ClnRpc.Tests/SerializerTests.fs
tests/DotNetLightning.ClnRpc.Tests/Tests.fs
tools/fsharp_msggen/fsharp_msggen/fsharp.py

c-lightning RPC does not allow rpc requests
to have `null` value in some parameters,
instead, if user does not want to specify an parameter,
they simply must not have that field.
This commit fixes null value handling in following cases.
* an optional array field when serializing with System.Text.Json
* Other optional fields with Newtonsoft.Json
It also uses Extension method instead of type extension
for `AddDNLJsonConverters()` so that it will be more C# friendly

Fix null value handling bug in ClnRpc

---

.github/workflows/build+test.yml
.github/workflows/gh-pages.yml
src/DotNetLightning.ClnRpc/DotNetLightning.ClnRpc.fsproj
src/DotNetLightning.ClnRpc/Requests.fs
src/DotNetLightning.ClnRpc/SystemTextJsonConverterExtensions.fs
src/DotNetLightning.ClnRpc/SystemTextJsonConverters.fs
tests/DotNetLightning.ClnRpc.Tests/SerializerTests.fs
tools/fsharp_msggen/fsharp_msggen/fsharp.py

Unlike Newtonsoft.Json, System.Text.Json does not
respect EnumMemberAttribute. (see: https://github.com/dotnet/runtime/issues/31081)
This caused an issue when sending request to c-lightning,
when you use System.Text.Json for serialization lib, and there
is a enum value in the request field, the field will be serialized into
an int, instead of a string. Thus causing RPC error.
This commit fixes it by using `JsonStringEnumConverterEx`
(which is taken from an issue comment of issue above).

cln: add JsonConverter for handling enum

---

.github/workflows/publish.yml
Directory.Build.props

It seems that specifying both `SymbolPackageFormat` and
`DebugType = embedded` causes an issue when publishing packages to
nuget.org, since former declares that symbols must be in a separate file.
But the latter declares it does not.
Ending up `.snupkg` files instead of `.nupkg` which supposed to contain
symbol file, but it does not. and nuget.org returns 400 when pushing
those packages.
This commit stops embedding symbols into dll (since that is not
recommended in https://github.com/dotnet/sourcelink).
And publish snupkg files with pdb.

stop embedding pdb into dll

---

src/DotNetLightning.Core/Serialization/Features.fs
tests/DotNetLightning.Core.Tests/Serialization.fs

This removes the use of intermediate bytearray when cloning the feature bitarray, it also adds a test that can prove this problem.

Serialization: fix SetFeature bug

---

src/DotNetLightning.Core/Serialization/Msgs/Msgs.fs
tests/DotNetLightning.Core.Tests/Serialization.fs
tests/DotNetLightning.Core.Tests/SerializationPropertyTests.fs

Added message type 1 (`warning`) as described in [BOLT #1](https://github.com/lightning/bolts/blob/master/01-messaging.md#the-error-and-warning-messages)
Added test which mirrors test for `error` message

Core(Serialization): added warning message type

---

src/DotNetLightning.ClnRpc/Client.fs

Async call will hanging when the lightningd does not return any response.
With some hack to dispose the socket explicitly, we can cancel correctly.

Cln async cancellation

---

src/DotNetLightning.Core/Serialization/Msgs/Msgs.fs
tests/DNLTestBase/Generators/Msgs.fs
tests/DotNetLightning.Core.Tests/Serialization.fs

Changed type of `Features` field in `UnsignedNodeAnnouncementMsg` to
`Result<FeatureBits, FeatureError>` in order to handle cases with invalid
or unknown features without throwing an exception during deserialization.

Core(Serialization): made UnsignedNodeAnnouncementMsg.Features a Result

---

src/DotNetLightning.ClnRpc/Client.fs
src/DotNetLightning.ClnRpc/ManuallyDefinedTypes.fs
src/DotNetLightning.ClnRpc/NewtonsoftJsonConverters.fs
src/DotNetLightning.ClnRpc/Plugin/PluginServerBase.fs
src/DotNetLightning.ClnRpc/Primitives.fs
src/DotNetLightning.ClnRpc/Requests.fs
src/DotNetLightning.ClnRpc/SystemTextJsonConverters.fs
tests/DotNetLightning.ClnRpc.Tests/SerializationTests.fs
tests/DotNetLightning.ClnRpc.Tests/SerializerTests.fs
tools/fsharp_msggen/fsharp_msggen/fsharp.py

When a user wants to set a custom JsonConverter type for ClnClient or plugin, they can use the property for CliClient or PluginServerBase respectively to set their custom converters.
Currently, DNL was adding those custom converters *after* user internally defined converters, but JsonConverter will use a converter that matche first for the type. Thus user could never override.
This commit changes that order to fix.

change the order of adding json converter

---

src/DotNetLightning.ClnRpc/Client.fs
src/DotNetLightning.ClnRpc/Plugin/PluginServerBase.fs

JsonConverter raise an error when the converter settings has changed for each serialization.
By re-creating each time in request, now its good.

Create json converter options for each cln request

---

src/DotNetLightning.ClnRpc/DotNetLightning.ClnRpc.fsproj

According to the guidance it is recommended to fix the `FSharp.Core` version in case of library.
https://fsharp.github.io/fsharp-compiler-docs/fsharp-core-notes.html
Since the oldest .NET Version we want to support is 6.0, we should fix it to 6.0.0

Fix FSharp.Core version for DNL.Cln to 6.0.0
